<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Agencysalescenter_model extends CI_Model
{

    public $table = 'agencysalescenter';
    public $id = 'SalesCenterID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
//        $this->db->order_by($this->id, $this->order);
//        return $this->db->get($this->table)->result();

$query = $this->db->query("
SELECT a.*,b.CityName,c.AreaName FROM AgencySalesCenter a
LEFT JOIN City b ON a.CityID =  b.CityID
LEFT JOIN Area c ON a.AreaID =  c.AreaID
Order BY a.SalesCenterID DESC

");
return $query->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('SalesCenterID', $q);
	$this->db->or_like('AgencyID', $q);
	$this->db->or_like('AreaID', $q);
	$this->db->or_like('CityID', $q);
	$this->db->or_like('AsuradurID', $q);
	$this->db->or_like('SourceData', $q);
	$this->db->or_like('SalesCenterCode', $q);
	$this->db->or_like('SalesCenterName', $q);
	$this->db->or_like('StreetAddress', $q);
	$this->db->or_like('VillageAddress', $q);
	$this->db->or_like('SubDistrictAddress', $q);
	$this->db->or_like('CityAddress', $q);
	$this->db->or_like('PostalCode', $q);
	$this->db->or_like('PhoneNumber', $q);
	$this->db->or_like('FaxNumber', $q);
	$this->db->or_like('EmailAddress', $q);
	$this->db->or_like('IsActive', $q);
	$this->db->or_like('ActiveDate', $q);
	$this->db->or_like('Enddate', $q);
	$this->db->or_like('ReasonEnd', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('SalesCenterID', $q);
	$this->db->or_like('AgencyID', $q);
	$this->db->or_like('AreaID', $q);
	$this->db->or_like('CityID', $q);
	$this->db->or_like('AsuradurID', $q);
	$this->db->or_like('SourceData', $q);
	$this->db->or_like('SalesCenterCode', $q);
	$this->db->or_like('SalesCenterName', $q);
	$this->db->or_like('StreetAddress', $q);
	$this->db->or_like('VillageAddress', $q);
	$this->db->or_like('SubDistrictAddress', $q);
	$this->db->or_like('CityAddress', $q);
	$this->db->or_like('PostalCode', $q);
	$this->db->or_like('PhoneNumber', $q);
	$this->db->or_like('FaxNumber', $q);
	$this->db->or_like('EmailAddress', $q);
	$this->db->or_like('IsActive', $q);
	$this->db->or_like('ActiveDate', $q);
	$this->db->or_like('Enddate', $q);
	$this->db->or_like('ReasonEnd', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }


    function getCity($postData){
        $response = array();
        
        // Select record
/*
        $this->db->select('AgencyID,AgencyName');
        $this->db->where('AreaID', $postData['area']);
        $q = $this->db->get('Area');
*/      
$area_id = $postData['area'];
$q = $this->db->query("
SELECT a.CityID, a.CityName 
FROM City a

WHERE a.AreaID='$area_id'
");
        $response = $q->result_array();

        return $response;
    }

// =-=-=-=-

//getNewSalesCodeCode
public function getNewSalesCenterCode(){
    
    $now1 = explode(' ', microtime());
$now= $now1[1] ;
//print_r($now);die();  
    // $charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    $charset = "ABCDEFGHJKLMNPRTVWXYZ0123456789";
  $base = strlen($charset);
  $result = '';

  while ($now >= $base){
    $i = $now % $base;
    $result = $charset[$i] . $result;
    $now /= $base;
  }
  
//  return substr($result, -3);
    $hash = substr($result, -2);
    $cek = $this->db->query("SELECT SalesCenterCode FROM AgencySalesCenter  ")->result();    

    foreach($cek as $kode){
    
    $kode_ada []= $kode->SalesCenterCode;
    //echo $kode_ada;
    //echo"<br>";
}

//print_r($kode_ada);die();

if (in_array($hash, $kode_ada)){
$new_code = $hash =$this->getNewSalesCenterCode();          
  //echo "Match found";
}else{
$new_code =$hash;     
  //echo "Match not found";
  }


return $new_code;
    
}    


}

/* End of file Agencysalescenter_model.php */
/* Location: ./application/models/Agencysalescenter_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-04 04:56:36 */
/* http://harviacode.com */