<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Performanceunmatch_model extends CI_Model
{

    public $table = 'performanceunmatch';
    public $id = 'RowID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
   	
//        $this->db->order_by($this->id, $this->order);
//        return $this->db->get($this->table)->result();
        return $this->db->query('SELECT * FROM PerformanceUnMatch 
WHERE IsGenerateCorrection=0')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('RowID', $q);
	$this->db->or_like('ApplicationSource', $q);
	$this->db->or_like('BatchID', $q);
	$this->db->or_like('Month', $q);
	$this->db->or_like('Year', $q);
	$this->db->or_like('EmployeeID', $q);
	$this->db->or_like('OldSourceCode', $q);
	$this->db->or_like('NewSourceCode', $q);
	$this->db->or_like('Remark', $q);
	$this->db->or_like('ProposedDate', $q);
	$this->db->or_like('ProposedBy', $q);
	$this->db->or_like('ApprovalID', $q);
	$this->db->or_like('IsGenerateCorrection', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('RowID', $q);
	$this->db->or_like('ApplicationSource', $q);
	$this->db->or_like('BatchID', $q);
	$this->db->or_like('Month', $q);
	$this->db->or_like('Year', $q);
	$this->db->or_like('EmployeeID', $q);
	$this->db->or_like('OldSourceCode', $q);
	$this->db->or_like('NewSourceCode', $q);
	$this->db->or_like('Remark', $q);
	$this->db->or_like('ProposedDate', $q);
	$this->db->or_like('ProposedBy', $q);
	$this->db->or_like('ApprovalID', $q);
	$this->db->or_like('IsGenerateCorrection', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Performanceunmatch_model.php */
/* Location: ./application/models/Performanceunmatch_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-28 06:53:35 */
/* http://harviacode.com */